### ISSUE TITLE
Query forms breaks javascript based result formats

### ISSUE THREAD

**Issue by gesinn-it-gea** [gesinn-it-pub/mediawiki-extensions-PageForms#1]
see https://phabricator.wikimedia.org/T273272

**Comment by gesinn-it-wam** [comment]
[testwiki2.kdz.eu](https://testwiki2.kdz.eu/index.php/Special:Version) is running SMW 3.2.3. In this case, having SMW loaded before PF,
```
enableSemantics( 'example.com' );
wfLoadExtension( 'PageForms' );
```
has the effect described in https://phabricator.wikimedia.org/T273272.
It does not occur when loading the other way around:
```
wfLoadExtension( 'PageForms' );
enableSemantics( 'example.com' );
```
Using SMW 4, on the other hand, the order doesn't matter.

**Comment by gesinn-it-gea** [comment]
@krabina okay closing this issue?

**Comment by krabina** [comment]
I guess so. (Maybe we should add some info in the documentation?)
