### ISSUE TITLE
Option "requires" does not work

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-PageForms#16]
I tried the following:
```
{{#drilldowninfo:
 filters=Country (property=Country),
 Place (property=Place,requires=Country),
 |display parameters
```
But still, both filters are shown from the start. It should be that only the country filter is shown and the place filter appears once a country has been selected.

**Comment by gesinn-it-gea** [comment]
wrong repo?

**Comment by krabina** [comment]
Indeed, sorry: https://github.com/gesinn-it-pub/mediawiki-extensions-SemanticDrilldown/issues/18
