### ISSUE TITLE
Question - autocomplete and displaytitles

### ISSUE THREAD

**Issue by YOUR1** [gesinn-it-pub/mediawiki-extensions-PageForms#20]
I just saw this repo (referred by Toine through e-mail) and was wondering if this repo includes fixes for:
- Autocompletion fields with categories having more then 2000 items in it. We encountered that PF only shows a maximum of 1000 items. I've also fixed this in a private branch, but I can contribute this to this fork if needed. We've fixed this by adding an additional field attribute called "force autocomplete"
- Display titles translation in autocompletion fields - We've noticed that PF doesn't do this correctly. Ie. if you have a page with the same display title, it doesn't show you information of which page which is causing the user to be confused.

**Comment by gesinn-it-gea** [comment]
There has been some changes for autocompletion, also in combination with Display Title. We are using remote autocomplete on larger datasets without issues. So, there should be a solution for your item limit mentioned in your above comment. Give it a try.
