### ISSUE TITLE
#arraymap breaks with special characters

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-PageForms#38]
I am using the arraymap parser function in order to list subpages. This is working great as long as there are no special characters in the subpage names. E. g. an "&" will break this:

An example:
`{{SUBPAGES: {{FULLPAGENAME}}|depth=1 |sep=;}}`
gives you
`Testmanual/Kontakte;Testmanual/Reparatur;Testmanual/Rollen & Berechtigungen `

Then this will give you a list of supgages in an unordered list:
`{{#arraymap:{{SUBPAGES: {{FULLPAGENAME}}|depth=1 |sep=;}}|;|@@@|* [[@@@|{{#explode:@@@|/|-1}}]]|\n}}`
But the result is 

- Kontakte
- Reparatur
- Rollen &
- Berechtigungen

Because the result of @@@ is 
`Testmanual/Kontakte, Testmanual/Reparatur, Testmanual/Rollen &#38, Berechtigungen `

So there is something wrong in the arraymap parser function that could also result in errors on other places unrelated to subpages.

Setup
<html><body>

Software | Version
-- | --
MediaWiki | 1.35.9
PHP | 7.4.33 (apache2handler)
MySQL | 8.0.32-0ubuntu0.22.04.2
ICU | 70.1
Page Forms | 5.3.4.4 (301aad4) 13:01, 13. Sep. 2022

**Comment by gesinn-it-gea** [comment]
Did you try `{{FULLPAGENAMEE}}`?

**Comment by krabina** [comment]
FULLPAGENAMEE does not help, since the problem is not in the subpages, but the arraymap part

**Comment by krabina** [comment]
Oh, since this is working
`{{#arraymap:Testmanual/Kontakte, Testmanual/Reparatur, Testmanual/Rollen & Berechtigungen|;|@@@|@@@}}`
it is most likely a SubpageFun bug after all.

**Comment by krabina** [comment]
Hmm. but {{SUBPAGES: {{FULLPAGENAME}} }} delivers the correct results. It just breaks inside the arraymap

**Comment by gesinn-it-gea** [comment]
As an alternative, consider using SemanticExtraSpecialPropertie's "Subpage".

`{{#ask:[[{{FULLPAGENAME}}]]|?Subpage=|mainlabel=-}}`

**Comment by krabina** [comment]
Thank you, great idea. Wasn't even aware of this!
