### ISSUE TITLE
Use of SkinTemplateNavigation hook (used in PFFormEditAction::displayTab) was deprecated in MediaWiki 1.39

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-PageForms#44]
When using the latest version 5.3.4.6 (3017e9b) on MW 1.39, the following warnings show

```
Deprecated
: Use of SkinTemplateNavigation hook (used in PFFormEditAction::displayTab) was deprecated in MediaWiki 1.39. [Called from MediaWiki\HookContainer\HookContainer::run in /home/knowledge/test/includes/HookContainer/HookContainer.php at line 137] in
/home/knowledge/test/includes/debug/MWDebug.php
on line
381


Deprecated
: Use of SkinTemplateNavigation hook (used in PFHelperFormAction::displayTab) was deprecated in MediaWiki 1.39. [Called from MediaWiki\HookContainer\HookContainer::run in /home/knowledge/test/includes/HookContainer/HookContainer.php at line 137] in
/home/knowledge/test/includes/debug/MWDebug.php
on line
381
```

**Comment by krabina** [comment]
MediaWiki | 1.39.4
-- | --
PHP | 8.0.27 (litespeed)

**Comment by gesinn-it-ilm** [comment]
Replacement for **'SkinTemplateNavigation'** in MW 1.39 is **'SkinTemplateNavigation::Universal'**. 

That change has been introduced 8 months ago inside extension.json. ([7e3acf0](https://github.com/gesinn-it-pub/mediawiki-extensions-PageForms/commit/7e3acf0584aca39bee76bc3b0b0f6d9b4dd9da97))

After running _make ci_ and check deprecated warnings for 1.39, deprecared warnings from above regarding **SkinTemplateNavigation** hook are fixed. 

**extension.json:**
![Screenshot 2024-06-14 114001](https://github.com/gesinn-it-pub/mediawiki-extensions-PageForms/assets/169881483/6ae281b3-e962-49aa-b0fe-b35821dc7457)
