### ISSUE TITLE
Combobox with two dropdowns if values present

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-PageForms#53]
Input type combobox displays strange if values have been in the field before (does not happen if the field is empty):

![image](https://github.com/gesinn-it-pub/mediawiki-extensions-PageForms/assets/4318745/8c2d6bf3-38db-48f9-b838-7a9d15120d52)

https://test.knowledge.wiki/index.php?title=Reinhard_Lindner&action=formedit

Two dropdowns are shown.

**Comment by gesinn-it-gea** [comment]
On first sight it seems to be related to Multiinstance Templates. Other Comboboxes on the page, like "Geburtsort", looks good even if values are present.

https://test.knowledge.wiki/Form:Person?action=edit

**Comment by gesinn-it-gea** [comment]
could be caused by this JS error on the page:
![grafik](https://github.com/gesinn-it-pub/mediawiki-extensions-PageForms/assets/10398316/16670f8c-0c8b-4867-960f-10f885f9ffe7)

**Comment by krabina** [comment]
but SemanticCite is not even active (commented out in LocalSettings)

**Comment by gesinn-it-gea** [comment]
SemanticCite is active as per Special:Version

**Comment by krabina** [comment]
oops. Now it is not. Dos not change anything.

**Comment by krabina** [comment]
This is what we talked about yesterday, @gesinn-it-gea  @gesinn-it-evl .
